use_frameworks!

platform :ios, '10.0'



target 'jjutils_Example' do
  pod 'jjutils', :path => '../'

  target 'jjutils_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"
  end
end
